name: Deploy site
on:
  push:
  schedule:
  - cron: '47 4 * * 4'

jobs:
  linux1:
    name: Deploy website
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1
    - name: run install.sh
      uses: hapytex/github-actions/actions/run-install-sh@master
    - name: run the Makefile
      uses: hapytex/github-actions/actions/makefile@master
    - name: deploy site to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: out_
